package com.ssas.jibli.agent.repo.home

enum class HomeClickEvents {
    ORDER_SEE_ALL_CLICK,
    VIEW_SHOPS_CLICK,
    NOTIFICATIONS_CLICK,
    PICKUP_FROM_STORE,
    CANCEL_PICKUP,
    VIEW_MAP,
    MAKE_CALL_CLICK,
    DELIVER_TO_CUSTOMER,
    SEND_ORDER_OTP,
    CANCEL_ORDER_OTP,
    RESEND_ORDER_OTP,
    LOGOUT_BUTTON,
    MY_ORDERS,
    PICKUP_DELIVERIES
}